### ISSUE TITLE
Run Phantomjs & casper JS

### ISSUE THREAD

**Issue by AndreaGelmini** [niutech/node.php#22]
Hello
I am They try to run phantomjs with casperjs on my shared hosting but I'm having some problems.
keeps giving me this error

`Starting: node 'node_modules/casperjs'
Done. PID=572210
module.js:341
    throw err;
    ^

Error: Cannot find module '/xxxxx/xxxxx/public_html/node_modules/casperjs'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3`

Can you help me out? I do not understand how to run the scripts.

**Comment by niutech** [comment]
PhantomJS and CasperJS are standalone binaries, not Node JS scripts, so they will not work using node.php. However, you can edit function `node_start` in file `node.php` to run `casperjs` instead of `node`.

**Comment by AndreaGelmini** [comment]
But I have downloaded and installed from npm

https://www.npmjs.com/package/phantomjs
https://www.npmjs.com/package/casperjs

and everything went well .. ergo should run.

I have some doubts. However

PS. I can not understand how I should change the start function.

can you help out?
