### ISSUE TITLE
Switch to admin mode

### ISSUE THREAD

**Issue by SaqlainHussainShah** [niutech/node.php#28]
I am trying to run 
/node.php?install
But it is saying me to switch to admin mode. How can i switch to admin mode??
Error::
Node.php

Node.js is not yet installed. Switch to Admin Mode and Install it.
Powered by node.php

**Comment by niutech** [comment]
In order to enable admin mode, on line 13 of `node.php` set `ADMIN_MODE` to `true` (as stated in the README).
