### ISSUE TITLE
Node.js is not yet installed. Switch to Admin Mode and Install it

### ISSUE THREAD

**Issue by AngelTs** [niutech/node.php#33]
Node.js is not yet installed. Switch to Admin Mode and Install it

**Comment by bbenefield89** [comment]
Getting the same issue.

**Comment by sowere** [comment]
```
define("ADMIN_MODE", false); //set to true to allow unsafe operations, set back to false when finished
```

Set admin_mode to true on line no 13.

**Comment by niutech** [comment]
After enabling Admin mode (as per @sowere comment), open http://example.org/node.php?install. If it does not work, try going through [troubleshooting](https://github.com/niutech/node.php#troubleshooting).
