### ISSUE TITLE
 Error: 127 when running on godaddy.com shared hosting

### ISSUE THREAD

**Issue by wert134** [niutech/node.php#4]
Hi,
I have successfully installed node.js on my website using node.php, however when I try to use npm install to install the samples package or another package I get this output:

![capture](https://cloud.githubusercontent.com/assets/10771829/7159069/6a72f2da-e377-11e4-9edf-d6b59d433016.PNG)

Any help would be greatly appreciated. Node.php seems great.
Thanks.

**Comment by niutech** [comment]
Error 127 means "command not found". Probably there is something wrong with the path. I would [connect to your account by SSH](http://support.godaddy.com/help/article/4942/enabling-ssh-on-your-linux-shared-hosting-account) and type the `npm` command from there.

**Comment by niutech** [comment]
Closing since no updates on the issue.

**Comment by joonbizzle** [comment]
When typing in the `npm` command, the terminal window returns `-bash: npm: command not found`.

**Comment by niutech** [comment]
This means the `npm` binary is not in the path. Check if the `node` folder exists in the same folder where `node.php` is. Then check if `node/bin/npm` exists and has Execute permission set. Node.php executes `./node/bin/npm` under the hood.

Another option is the 32/64-bit mismatch, as described [here](http://askubuntu.com/questions/133389/no-such-file-or-directory-but-the-file-exists).
