### ISSUE TITLE
'tar' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ghost** [niutech/node.php#5]
I tried to install nodejs on xampp for testing it. After I'am using http://localhost/Nodejs/node.php?install its look like not installed because 'tar' is not recognized as an internal or external command. What should I do?

![image](https://cloud.githubusercontent.com/assets/1595701/9959879/654c843e-5e41-11e5-9188-855c5a1846a2.png)

**Comment by niutech** [comment]
You are on Windows and it does not have [`tar`](http://gnuwin32.sourceforge.net/packages/gtar.htm) program by default. Install it first.
