### ISSUE TITLE
Switch do Admin Mode

### ISSUE THREAD

**Issue by thedanheller** [niutech/node.php#6]
How do I switch to Admin Mode?

<img width="566" alt="node" src="https://cloud.githubusercontent.com/assets/1504716/10603726/6d2e347e-76fe-11e5-9bee-f583546bbca8.png">

Many thanks!

**Comment by daniloprates** [comment]
sorry, found it. i thought it was something I should do on my hosting

**Comment by tmess567** [comment]
Did you solve this?

**Comment by thedanheller** [comment]
yes, thanks

**Comment by tmess567** [comment]
I am facing the same problem. Could you help me through it?

**Comment by thedanheller** [comment]
oh sorry, I can't remember. I've found the solution at the time, but I'm no longer using node.php.

Looking through the code I've found [this bit](https://github.com/niutech/node.php/blob/master/node.php#L13). Maybe you just need to change it to true.

**Comment by tmess567** [comment]
Oh! that was silly, Thanks a lot

**Comment by thedanheller** [comment]
no probls =]

**Comment by niutech** [comment]
It is described in the [README](https://github.com/niutech/node.php/blob/master/README.md#commands) file.
