### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by scratchyone** [niutech/node.php#8]
I am trying to run npm install on my server and it returns:
Node.php

Running: npm node/bin/npm express
Failed. Error: 126

I was trying to install express. Check out my error here: scratchyone.com/runnode/index.php?npm=express

**Comment by niutech** [comment]
If a command is found but is not executable, the return status is 126.
Maybe it is because your URL is invalid. It should be:
http://scratchyone.com/runnode/index.php?npm=install+express

**Comment by scratchyone** [comment]
It still returns 126.

**Comment by niutech** [comment]
There is some problem with your server configuration. While starting node it shows the error:
`error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`. Maybe this is a problem with 32/64-bit architecture?

Do you have a SSH access to your server? Then log in and try to manually run `node/bin/npm install express`. Otherwise use [PHPShell](http://phpshell.sourceforge.net/) to do this.

**Comment by scratchyone** [comment]
Do I need sudo access? I don't have that.

**Comment by niutech** [comment]
No, you don't need root privileges unless you want to apt-get install packages.

**Comment by scratchyone** [comment]
It returnes "-bash: node/bin/npm: Permission denied"

**Comment by niutech** [comment]
Check with `ls -lh` who owns the file and what are the permissions. Maybe node.php is acting as another user. Then you will need to get the root access to change ownership.

**Comment by scratchyone** [comment]
drwxr-xr-x  4 scratchywon scratchywon 4.0K Dec  3 12:33 ./ //blue
drwxr-xr-x 14 scratchywon scratchywon 4.0K Dec  2 12:36 ../ //blue
-rw-r--r--  1 scratchywon scratchywon 4.7K Dec  3 12:33 index.php
drwxr-xr-x  6 scratchywon scratchywon 4.0K Oct 23  2014 node/
drwxr-xr-x  3 scratchywon scratchywon 4.0K Dec  2 12:41 node-v0.10.33-linux-x86/ //blue
-rw-r--r--  1 scratchywon scratchywon  127 Dec  3 12:36 nodeout
-rw-r--r--  1 scratchywon scratchywon    6 Dec  3 12:36 nodepid
-rw-r--r--  1 scratchywon scratchywon  316 Dec  2 13:02 server.js

**Comment by scratchyone** [comment]
node/ is also blue

**Comment by scratchyone** [comment]
I ran chmod 755 on node, node/bin and node/bin/npm

**Comment by niutech** [comment]
And does it fix the permission problem? If not, try checking for missing libraries using `ldd node/bin/npm`

**Comment by scratchywon** [comment]
I think it did. Thanks!

On Thursday, December 3, 2015, niu tech <notifications@github.com> wrote:

> And does it fix the permission problem? If not, try checking for missing
> libraries using ldd node/bin/npm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/niutech/node.php/issues/8#issuecomment-161780218>.
>


-- 
*sincerely*,
Connor S.

**Comment by scratchywon** [comment]
Yep.

On Thursday, December 3, 2015, Minecraft Teleport <scratchywon@gmail.com>
wrote:

> I think it did. Thanks!
>
> On Thursday, December 3, 2015, niu tech <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> And does it fix the permission problem? If not, try checking for missing
>> libraries using ldd node/bin/npm
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/niutech/node.php/issues/8#issuecomment-161780218>.
>>
>
>
> --
> *sincerely*,
> Connor S.
>
>
>
>

-- 
*sincerely*,
Connor S.

**Comment by niutech** [comment]
That's great!
