### ISSUE TITLE
Better options available

### ISSUE THREAD

**Issue by kellysutton** [niutech/node.php#9]
Not sure how I came across this project, but there are probably better approaches out there that are also affordable. An approach like this is subject to many less-than-ideal solutions, along with opening up some pretty big security holes. You're likely better off cutting out PHP entirely and just sticking with NodeJS on its own.

There are a few services out there that can host NodeJS projects affordably, including [Heroku](https://www.heroku.com/). They've also got a great getting started article with NodeJS: https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

Hope this helps!

**Comment by niutech** [comment]
Of course there are better options, but this projects shows that it is possible to run node.js on a PHP shared hosting, which is the most affordable hosting type today. Heroku is free, but has a 6hr/day downtime, which is a serious no-go. Finally, there is a big "run it at your own risk" warning in the README. I give the tool, decision belongs to users.
